spring:
  dataSource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://nwdpdmamchcbla:0dddb79cc9139d191b97c936a3648e169562d5c7c22780212025a9b7c35bf845@ec2-3-227-195-74.compute-1.amazonaws.com:5432/d89dd16c5v7ud0
    username: nwdpdmamchcbla
    password: 0dddb79cc9139d191b97c936a3648e169562d5c7c22780212025a9b7c35bf845
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  messages:
    basename: messages/messages
    encoding: UTF-8
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 427478828214-4ee1v120n6d89vo01tka49k52uisos5n.apps.googleusercontent.com
            client-secret: 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
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
              - https://www.googleapis.com/auth/youtubepartner

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

jwt:
  token:
    header: Authorization
    issuer: ShareTube
    clientSecret: DD08B39A2323170BA2BC68A5888463F4BD875B8A4638F8B17A9CA9B8E1496D0679CB6266DCD96B3CD812FF3C9EDD6E84520507E5A0F51F53F9220BC23B275817
    expirySeconds: 3600

youtube:
  key: AIzaSyAG5CtIFNO1Lb_Sq0wL8ald6O37no69BYE