jasypt:
  encryptor:
    password: you shall not pass
spring:
  dataSource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://3.34.252.182:5432/sharetube
    username: postgres
    password: dlduwls0822!
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: 1018
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  cache:
    type: redis
  redis:
    host: 3.34.252.182
#    host: localhost
    port: 6379
  messages:
    basename: messages/messages
    encoding: UTF-8
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 427478828214-4ee1v120n6d89vo01tka49k52uisos5n.apps.googleusercontent.com
            client-secret: ENC(a0z5Z8cn+ZFlyGPL4e1vzdP7O1M8duFamGKBp/kVdXtneRi9YFmTLLgwD0qS8vBfzo19TFcQYfMJi7zUOrUNKWYBxwtlfoSEtw7ABE3pJ3I=)
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
              - https://www.googleapis.com/auth/youtubepartner

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

jwt:
  token:
    header: Authorization
    issuer: ShareTube
    clientSecret: ENC(ZgACQglU4nh1H7fEy7rXpJoV6PZnXklQRqE8WZrsPKYFl+tvAx5H0VZ2e7SNQ52KPtHt/oRUO9CBWBWvIINiHB4A6AvJN34LaOdNkaYfr+SDJ/CQXckfMII7h6f11Na8NVUTlngM5sSLpYkJn/ofNz3kpHH26AqSXqx7QcdRO6E4qFy7wIjJbEnbq7RzWat6OOZSnWqC2r6VPxxu/cV05tQOEr3xqZb1ih2LDuyTF2g=)
    expirySeconds: 3600

youtube:
  key: ENC(ebLSvvT+LSa7d1yALUi/moyEhsj5zWhQg48OS/H98fAAd5mhIpDLO48I3eA1dIpMdbbrYXWmo8HT8AzuTRCQGmByzAW1YTF7SwqINeQTZLw=)